application: engineapp2
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
# Serve favicon
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

# Serve static files (CSS, JS, etc.)
- url: /static
  static_dir: static

# Serve your app (Jinja templates via webapp2)
- url: /.*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: "2.6"
